libraryRecord:
  url: https://gateway.bibliocommons.com/v2/libraries/chipublib/bibs
museums:
  Adler Planetarium: S126C2108681
  American Writers Museum: S126C2108182
  Art Institute of Chicago: S126C2108684
  Bronzeville Children's Museum: S126C2108687
  Brookfield Zoo: S126C2108691
  Chicago Botanic Garden: S126C2108692
  Chicago Children's Museum: S126C2108694
  Museum of Science and Industry: S126C2108707
  Shedd Aquarium: S126C2108712
